title:            Friendly Tester
description:      "My Thoughts on Software Testing"
logo:             logo.png
disqus_shortname: friendlytester
share:            true
dropcap:			     false
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url: https://thefriendlytester.co.uk

# Owner/author information
owner:
  name:           Richard Bradshaw
  avatar:         richard.jpg
  email:          blog@friendlytesting.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Software Tester, speaker and trainer at Friendly Testing. BossBoss at <a target="_blank" href="https://ministryoftesting.com">Ministry of Testing</a>. <a target="_blank" href="https://www.youtube.com/channel/UC0QZWhi0ojqNte3ey7RD0qQ">Whiteboard Testing</a> creator. Striving to improve the testing craft.
  # Social networking links used in footer. Update and remove as you like.
  twitter:        FriendlyTester
  #facebook:       
  github:         FriendlyTester
  instagram:      FriendlyTester
  linkedin:       FriendlyTester
  youtube:        channel/UC0QZWhi0ojqNte3ey7RD0qQ
  rss:            friendlytester
  # For Google Authorship https://plus.google.com/authorship
  #google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-45075718-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If there is a sponsor
sponsor:
  active: true
  text: "TestBash, the software testing conference by Ministry of Testing is heading to San Francisco on November 8-9th 2018!"
  link: https://ministryoftesting.com/events/testbash-san-francisco-2018?utm_medium=banner&utm_source=Friendlytester
  
# Links to include in footer navigation
# For external links add external: true
links:
  - title: Blog
    url: /
  - title: Events
    url: /events
  - title: Online Courses
    url: /training/online
  - title: Training
    url: /training
  - title: Whiteboard Testing
    url: /whiteboardtesting
  - title: Speaker Rider
    url: /speaker-rider
  - title: Sponsor
    url: /sponsor

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers:
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
